### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by daemianmack** [hiredman/clj-http-lite#12]
I'm particularly interested in the work from PR #10.

**Comment by trptcolin** [comment]
:+1: I'm interested in https://github.com/hiredman/clj-http-lite/commit/51ddc564e19bfc3cd791631c59a2643fcacdb778 - just going to roll a stopgap release to my clojars account for now though.

**Comment by hiredman** [comment]
sorry, terrible at email, pushed 0.3.0 with #10

**Comment by daemianmack** [comment]
Thanks!
